# Generated by Django 5.2.8 on 2025-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://grandseasonscoquitlam.com/img/placeholders/comfort_food_placeholder.png', max_length=600),
        ),
    ]
